export const NOTIFICATION_SHOW_ERROR_MESSAGE = 'NOTIFICATION_SHOW_ERROR_MESSAGE';
export const NOTIFICATION_SHOW_SUCCESS_MESSAGE = 'NOTIFICATION_SHOW_SUCCESS_MESSAGE';
export const NOTIFICATION_SHOW_INFO_MESSAGE = 'NOTIFICATION_SHOW_INFO_MESSAGE';
export const NOTIFICATION_CLOSE_MESSAGE = 'NOTIFICATION_CLOSE_MESSAGE';
